export const areasOfLahore = [
  { name: "Select - If Pick Up Order", fee: 0 },
  { name: "Dehli Colony", fee: 0 },
  { name: "Gizri", fee: 50 },
  { name: "Clifton Block 1", fee: 100 },
  { name: "Clifton Block 2", fee: 50 },
  { name: "Clifton Block 4", fee: 50 },
  { name: "DHA Phase 1", fee: 100 },
  { name: "DHA Phase 2 Ext", fee: 50 },
  { name: "DHA Phase 4", fee: 50 },
  { name: "DHA Phase 5", fee: 50 },
  { name: "DHA Phase 6", fee: 100 },
  { name: "DHA Phase 7 Ext", fee: 150 },
  { name: "DHA Phase 8 Emaar", fee: 200 },
  { name: "Qauamabad", fee: 150 },
  { name: "Defence View", fee: 150 },
  { name: "Bath Island", fee: 50 },
  { name: "Hijrat Colony", fee: 50 },
  { name: "Civil Lines", fee: 50 },
  { name: "Cantt", fee: 50 },
  { name: "Gulshan e Sikandarabd", fee: 100 },
  { name: "Sultanabad", fee: 50 },
  { name: "Kala Pull", fee: 150 },
  { name: "Rancho Line", fee: 250 },
  { name: "Neelum Colony", fee: 50 },
  { name: "PIDC", fee: 50 },
  { name: "Saddar", fee: 150 },
  { name: "Garden", fee: 250 },
  { name: "Soldier Bazaar", fee: 300 },
  { name: "Agra Taj", fee: 250 },
  { name: "Tariq Road", fee: 250 },
  { name: "Numaish", fee: 300 },
  { name: "Karsaz", fee: 300 },
  { name: "Shahrah e Faisal", fee: 250 },
  { name: "Manzoor Colony", fee: 250 },
  { name: "Mahmoodabad", fee: 250 },
  { name: "Azam Basti", fee: 150 },
  { name: "Azam Town", fee: 250 },
  { name: "Chanesar Goth", fee: 250 },
  { name: "Parsi Colony", fee: 150 },
  { name: "Akhtar Colony", fee: 150 },
  { name: "Korangi", fee: 300 },
  { name: "TAPU", fee: 100 },
  { name: "Balouch Colony", fee: 250 },
  { name: "Sindhi Muslim", fee: 250 },
  { name: "I I Chundigar", fee: 100 },
  { name: "Pakistan Chowk", fee: 150 },
  { name: "Light House", fee: 250 },
  { name: "Boltan Market", fee: 250 },
  { name: "Gulshan Iqbal", fee: 700 },
  { name: "Gulistan e Jauhar", fee: 600 },
  { name: "Kharadar", fee: 250 },
  { name: "Liyari", fee: 300 },
  { name: "Main Tower", fee: 100 },
  { name: "Custom House", fee: 150 },
  { name: "Kemari", fee: 250 },
  { name: "Sheersha", fee: 300 },
  { name: "Dockyard", fee: 250 },
  { name: "Site Area", fee: 300 },
  { name: "West Wharaf", fee: 250 },
  { name: "Maripur", fee: 300 },
  { name: "Shipyard", fee: 250 },
  { name: "Fishri", fee: 300 },
  { name: "PECHS All Block", fee: 250 },
  { name: "Gora Qubristan", fee: 250 },
  { name: "Lines Area", fee: 250 }
];
